import type { Metadata } from "next";
import "../globals.css";
import { SanityLive } from "@/sanity/lib/live";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Shop Now",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
    <html lang="en">
      <body>
        <main>
          <Navbar/>
        {children}
        <SanityLive/>
        </main>
      </body>
    </html>
    </ClerkProvider>
  );
}
